### ISSUE TITLE
[FEATURE] Add StylableMessageBox

### ISSUE THREAD

**Issue by wolframhaussig** [Assorted-Development/winforms-stylable-controls#41]
We should consider adding a `StylableMessageBox` which shows a messagebox that can be styled the same way as our other controls to have matching styles.

**Comment by wolframhaussig** [comment]
@Nockiro I just started working on this issue and found that this might be the wrong repo for this:  
`MessageBox.Show` works by showing the form as part of the call to `MessageBox.Show` and returns the result. When we add the `StylableMessageBox` to this repo, we would need to return the form only, as we do not know how the caller wants it to be styled.

On the other hand, this is not a control itself, it is only a collection of already existing controls. My proposal would be to add the `StylableMessageBox` to the themes repository, where we could add an additional `ITheme` parameter to the call. This way, we could style and show the form within the call to `Show` as expected.

What do you think?

PS: The same goes for #42 where we want to add a feature similar to VB.NET `Interaction.InputBox`

**Comment by Nockiro** [comment]
Interesting question.  
I think this depends on how we want to implement the MessageBox: 
  - Is it its own `Form` with all the controls necessary? 
  --> Good candidate to remain in this repository as it's a) something to be themed instead of something _controlling_ the theming and b) Forms are `Control`s (via `ContainerControl` -> `ScrollableControl`)
  - Do we want to continue using Windows' MessageBox as `Windows.Forms.MessageBox` does via their P/Invoke call?
  --> Better candidate for winforms-themes (although still not that good since I see that repo really as something controlling/implementing the theme mechanism and only that)

**Comment by wolframhaussig** [comment]
I would vote for (1) - create a custom form. My issue is that:
a) this is not a completely new control - it just reuses existing controls
b) the user would need to create the form itself and has no easy access to `MessageBox.Show` as he has to style the form instance before showing
c) we would return not a single control - it would be a collection of controls where all of them need to be styled without knowing which controls exist in the form

Creating it in the themes library would solve the issue as the styling could be done automatically.

**Comment by Nockiro** [comment]
I think with your PR implementation as well as the currently pending PR for the new theming variable system would at least mitigate issue c). As for b), the PR solves that elegantly, too - so... this would just leave issue a) for which you could argue that we already have this with other controls, just on a deeper level.  
The ComboBox for example also consists of multiple elements, they are just not on a deeper level than .NET - and I don't even think that it's bad that multiple controls are combined into one - it's still a control with a specific purpose that just happens to have multiple stylable areas.
